services:
  ai-accountant-agent:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped

    ## resources limits 8GB memory and 2 CPU
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '2.0'
